FROM jhonatans01/python-dlib-opencv

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get -y update && apt-get install -y netcat
RUN pip install --upgrade pip



WORKDIR /app

EXPOSE 8000

COPY requirements.txt /app/
RUN mkdir /app/static
RUN mkdir /app/media
RUN mkdir /app/accounts_face_recognition
RUN mkdir /app/accounts_face_recognition/model_data



RUN pip3 install -U pip wheel cmake
RUN pip3 install dlib face_recognition gunicorn
RUN pip3 install -r requirements.txt

RUN apt update
RUN apt install -y nginx

COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

COPY . .

ENTRYPOINT ["sh","/app/entrypoint.sh"]