# Generated by Django 4.2.4 on 2023-08-24 10:13

import articles.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Article Title')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=articles.models.article_featured_image_directory_path)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('force_highlighted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=articles.models.article_file_directory_path, verbose_name='Pdf file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
